name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "infra"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        run: |
          cd infra
          az group create --name myResourceGroup --location eastus
          az deployment group create --resource-group myResourceGroup --template-file ./main.bicep
